### ISSUE TITLE
small zone overflow

### ISSUE THREAD

**Issue by k4r3l01** [callofduty4x/CoD4x_Server#148]
when i try to run server i give this error
Sys_Error: Z_Malloc: failed on allocation of 60 bytes from the small zone
Bad thread localBad thread local

**Comment by k4r3l01** [comment]
now i tried to run server with yours precompiled linux server and its same

**Comment by D4edalus** [comment]
what distro are you on? are you maybe out of memory :P? .. i mean its working for 600 other servers

**Comment by k4r3l01** [comment]
sever is ubuntu and we have free about 20GB of ram so i dont know where is problem
and here is complete console output 
https://pastebin.com/QCurHU1s

**Comment by k4r3l01** [comment]
so i now tried to start server
1. without mod its same
2 without mod and without config server start correctly
3. with mod but without configs server starts correctly

**Comment by k4r3l01** [comment]
and what i see in qcommon_mem.c so small zone is only for cvars and cmds

**Comment by k4r3l01** [comment]
so small zone must be increased for me default in qcommon_mem.c is 
int s_smallZoneTotal = 512 * 1024;
but i must use 
int s_smallZoneTotal = 1024 * 1024;
its will be great if this will be possible to make in dvar and not edit source of cod4x

**Comment by T-Maxxx** [comment]
Maybe re-create your configs?

**Comment by AlexanderCurl** [comment]
THis huge amount of configs makes the server crashes. Insert in 1 and will be fine.

**Comment by k4r3l01** [comment]
we are using openwarfare mod and this mod using this config system for better transparency so i think its not good to decrease number of configs helps because this crash have nothing with number of configs but with number of dvars

**Comment by D4edalus** [comment]
after a few days of running one of my servers crashed with the same bug. something is going on there.

**Comment by icekobrin** [comment]
All 3 of my servers encountered this error today.
Sys_Error: Z_Malloc: failed on allocation of 52 bytes from the small zone

**Comment by T-Maxxx** [comment]
Possible error: requested 52 bytes, allocated 4k, in use 52. And so on...

**Comment by D4edalus** [comment]
i dont quite understand what you mean

i've increased zone size in a recent commit. if a crash happens again i'd start looking for memory leaks.

**Comment by T-Maxxx** [comment]
If someone want to investigate it further:
Got this output for custom scrupt located in mod directory.
https://gist.github.com/T-Maxxx/3633285814503cfadaa5a929d0d05ca9

**Comment by volkv** [comment]
@D4edalus ok, start testing new build. cuz build 2000 caused 1 of my 8th servers drop like every 1-2 hours

**Comment by volkv** [comment]
16 hours run - no crashes. I believe problem is solved

**Comment by Kingwolf123** [comment]
Yup same error occuring 
MingW Build 2000 
Sys_Error: Z_Malloc: failed on allocation of 36 bytes from the small zone

Will update to 17.2 Version to update on the issue

**Comment by D4edalus** [comment]
still crashing on build 2011. 
however, increasing small zone delayed crashing. probably a memory leak.

**Comment by ingre** [comment]
omg again this problem, guys help me pls, I add new mod and some problem
just start test mod in pc, crash 
Sys_Error: Z_Malloc: failed on allocation of 32 bytes from the small zone
